language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
- chmod +x gradle/wrapper/gradle-wrapper.jar
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    secure: zbrlGnn3XROnnOnu3QIKb+LHTkGbJrqW3xyUNE/egHZ2F6214IrW3nMQ1UCWcf3BgrcA/t+ATPUGT0DJBUbzRypQrJadkG82KavGllAhd6KUBSKGFEGq4+6ug8g+1OhOs/EyxbMH98dftPO9IABs0bByHARU8EQEvaRTkX+MvaF0I6Ni/3nFoYn2xf6aSEZ8/S20co59BN+1GjLTippJERTREWsj6A5LDlsyH5Dw9REbhp2UXRbR2zlw2hbQu6HxTLSf8FAarEh0NsXI5EeCkO2TJsL1R0CejFznPRIk2WLr4TebgWY6Hdk3EUlwuM/4JqEqgml0yLg8/BpG3oB/iXJaYZOhRW7ZALJ9KFCD2CKI4Kdi1CeryGtabl6FfQene9vPDxGkmolTOFtglW5MoHIpLVE/oni0GTQEaqHhdYqCBJ/gHLx+Mrc433cDgIEd9RNqCa6vNzmfS7h7+yHKH4OxzK+PCDezsTvrwca1VCMhKBtdT9YI+hOys5J76Gf42zW8EpY9BsC05H3g+Pp0pbVIe6rmu5RShgJUne16LlkrsLKr03mZes0XsYOYA7VgnMMLFMwd/urbtcKOe1YClfKiAuBcFrpdEbSS8boqkxLbG0BmfcyXyf35eFhKFghom0dZNLa+BgMQ0os7vk3IE25f46/rzmpZRmAUlsW7aco=
    on_success: always
    on_failure: always