server:
  port: 5000

logging:
  file: server_log.log

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

graphiql:
  mapping: /graphiql
  endpoint: /graphql
  enabled: true

studi:
  security:
    auth:
      secret: helasecret