type MutationRoot {
    createUser(input: PermissionsInput!): ID!
}

input PermissionsInput {
    permissions: [String!]!
}

type QueryRoot {
    getUserPermissions(id: ID!): [String]!
    secureGet: String!
}

schema {
    mutation: MutationRoot
    query: QueryRoot
}