type Hello {
    value: String!
    getComplexThing(bar: String!): String!
}

input HelloInput {
    foo: String!
}

type Query {
    hello(input: HelloInput!): Hello!
}

type Mutation {
    logAString(str: String!): String!
}


schema {
    query: Query
    mutation: Mutation
}